PELVIS = 0
SPINE_NAVAL = 1
SPINE_CHEST = 2
NECK = 3
CLAVICLE_LEFT = 4
SHOULDER_LEFT = 5
ELBOW_LEFT = 6
WRIST_LEFT = 7
HAND_LEFT = 8
HANDTIP_LEFT = 9
THUMB_LEFT = 10
CLAVICLE_RIGHT = 11
SHOULDER_RIGHT = 12
ELBOW_RIGHT = 13
WRIST_RIGHT = 14
HAND_RIGHT = 15
HANDTIP_RIGHT = 16
THUMB_RIGHT = 17
HIP_LEFT = 18
KNEE_LEFT = 19
ANKLE_LEFT = 20
FOOT_LEFT = 21
HIP_RIGHT = 22
KNEE_RIGHT = 23
ANKLE_RIGHT = 24
FOOT_RIGHT = 25
HEAD = 26
NOSE = 27
EYE_LEFT = 28
EAR_LEFT = 29
EYE_RIGHT = 30
EAR_RIGHT = 31

PARENT_INDICES = {
    SPINE_NAVAL: PELVIS,
    SPINE_CHEST: SPINE_NAVAL,
    NECK: SPINE_CHEST,
    CLAVICLE_LEFT: SPINE_CHEST,
    SHOULDER_LEFT: CLAVICLE_LEFT,
    ELBOW_LEFT: SHOULDER_LEFT,
    WRIST_LEFT: ELBOW_LEFT,
    HAND_LEFT: WRIST_LEFT,
    HANDTIP_LEFT: HAND_LEFT,
    THUMB_LEFT: WRIST_LEFT,
    CLAVICLE_RIGHT: SPINE_CHEST,
    SHOULDER_RIGHT: CLAVICLE_RIGHT,
    ELBOW_RIGHT: SHOULDER_RIGHT,
    WRIST_RIGHT: ELBOW_RIGHT,
    HAND_RIGHT: WRIST_RIGHT,
    HANDTIP_RIGHT: HAND_RIGHT,
    THUMB_RIGHT: WRIST_RIGHT,
    HIP_LEFT: PELVIS,
    KNEE_LEFT: HIP_LEFT,
    ANKLE_LEFT: KNEE_LEFT,
    FOOT_LEFT: ANKLE_LEFT,
    HIP_RIGHT: PELVIS,
    KNEE_RIGHT: HIP_RIGHT,
    ANKLE_RIGHT: KNEE_RIGHT,
    FOOT_RIGHT: ANKLE_RIGHT,
    HEAD: NECK,
    NOSE: HEAD,
    EYE_LEFT: HEAD,
    EAR_LEFT: HEAD,
    EYE_RIGHT: HEAD,
    EAR_RIGHT: HEAD,
}

CHILD_INDICES = {
    SPINE_NAVAL: [SPINE_CHEST],
    SPINE_CHEST: [NECK, CLAVICLE_LEFT, CLAVICLE_RIGHT],
    CLAVICLE_LEFT: [SHOULDER_LEFT],
    SHOULDER_LEFT: [ELBOW_LEFT],
    ELBOW_LEFT: [WRIST_LEFT],
    WRIST_LEFT: [HAND_LEFT, THUMB_LEFT],
    HAND_LEFT: [HANDTIP_LEFT],
    CLAVICLE_RIGHT: [SHOULDER_RIGHT],
    SHOULDER_RIGHT: [ELBOW_RIGHT],
    ELBOW_RIGHT: [WRIST_RIGHT],
    WRIST_RIGHT: [HAND_RIGHT, THUMB_RIGHT],
    HAND_RIGHT: [HANDTIP_RIGHT],
    PELVIS: [SPINE_NAVAL, HIP_LEFT, HIP_RIGHT],
    HIP_LEFT: [KNEE_LEFT],
    KNEE_LEFT: [ANKLE_LEFT],
    ANKLE_LEFT: [FOOT_LEFT],
    HIP_RIGHT: [KNEE_RIGHT],
    KNEE_RIGHT: [ANKLE_RIGHT],
    ANKLE_RIGHT: [FOOT_RIGHT],
    NECK: [HEAD],
    HEAD: [NOSE, EYE_LEFT, EAR_LEFT, EYE_RIGHT, EAR_RIGHT],
}

INDICES_TO_STRINGS = {
    PELVIS: 'PELVIS',
    SPINE_NAVAL: 'SPINE NAVAL',
    SPINE_CHEST: 'SPINE CHEST',
    NECK: 'NECK',
    CLAVICLE_LEFT: 'CLAVICLE L',
    SHOULDER_LEFT: 'SHOULDER L',
    ELBOW_LEFT: 'ELBOW L',
    WRIST_LEFT: 'WRIST L',
    HAND_LEFT: 'HAND L',
    HANDTIP_LEFT: 'HANDTIP L',
    THUMB_LEFT: 'THUMB L',
    CLAVICLE_RIGHT: 'CLAVICE R',
    SHOULDER_RIGHT: 'SHOULDER R',
    ELBOW_RIGHT: 'ELBOW R',
    WRIST_RIGHT: 'WRIST R',
    HAND_RIGHT: 'HAND R',
    HANDTIP_RIGHT: 'HANDTIP R',
    THUMB_RIGHT: 'THUMB R',
    HIP_LEFT: 'HIP L',
    KNEE_LEFT: 'KNEE L',
    ANKLE_LEFT: 'ANKLE L',
    FOOT_LEFT: 'FOOT L',
    HIP_RIGHT: 'HIP R',
    KNEE_RIGHT: 'KNEE R',
    ANKLE_RIGHT: 'ANKLE R',
    FOOT_RIGHT: 'FOOT R',
    HEAD: 'HEAD',
    NOSE: 'NOSE',
    EYE_LEFT: 'EYE L',
    EAR_LEFT: 'EAR L',
    EYE_RIGHT: 'EYE R',
    EAR_RIGHT: 'EAR R',
}
